### QueryString Params
GET http://127.0.0.1:9101/v1.0/invoke/demo-hello-srv/method/params/get?name=bluefrog&age=14

### QueryString Params miss some params
GET http://127.0.0.1:9101/v1.0/invoke/demo-hello-srv/method/params/get?name=bluefrog

### body-post
POST http://127.0.0.1:9101/v1.0/invoke/demo-hello-srv/method/params/body
content-type: application/json

{
  "name": "bluefrog",
  "age": 13
}

### body-post
POST http://127.0.0.1:9101/v1.0/invoke/demo-hello-srv/method/params/body
content-type: application/json

{
  "name": "bluefrog",
  "age": "aaaa"
}

### body-post
POST http://127.0.0.1:9101/v1.0/invoke/demo-hello-srv/method/params/body
content-type: application/json

{
  "name": "bluefrog"
}

### body-post
POST http://127.0.0.1:9101/v1.0/invoke/demo-hello-srv/method/params/body
content-type: application/json

{

}

### form-post
POST http://127.0.0.1:9101/v1.0/invoke/demo-hello-srv/method/params/form
content-type: application/form

name=bluefrog&age=12

###